/**
 * Static fixtures for the demo workspaces. Anything random (dates, amounts, who did what) is
 * drawn from the seeded generator in `seed.ts`; this file holds the hand-written names.
 */
import type { BillingType, ClientInput, ProjectStatus } from '@ledgerline/shared';

export const DEMO_TODAY = '2026-06-30';
export const DEMO_PASSWORD = 'password123';

export interface SeedUser {
  key: 'ada' | 'marcus' | 'priya';
  name: string;
  email: string;
}

export const USERS: SeedUser[] = [
  { key: 'ada', name: 'Ada Okafor', email: 'ada@northlight.studio' },
  { key: 'marcus', name: 'Marcus Lindqvist', email: 'marcus@northlight.studio' },
  { key: 'priya', name: 'Priya Raman', email: 'priya@northlight.studio' },
];

export type SeedClient = ClientInput & { key: string };

export const NORTHLIGHT_CLIENTS: SeedClient[] = [
  {
    key: 'aldergrove',
    name: 'Aldergrove Botanic Gardens',
    company: 'Aldergrove Botanic Gardens Society',
    email: 'visitor.experience@aldergrovegardens.ca',
    phone: '+1 604 555 0142',
    addressLine1: '3800 Cedar Crescent',
    addressLine2: '',
    city: 'Vancouver',
    region: 'BC',
    postalCode: 'V6J 2R4',
    country: 'Canada',
    taxId: 'BN 81234 5678 RT0001',
    paymentTermsDays: 30,
    notes: 'Seasonal signage programme; wayfinding refresh every spring.',
    status: 'active',
  },
  {
    key: 'fenwick',
    name: 'Fenwick & Daughters',
    company: 'Fenwick & Daughters Ltd',
    email: 'eleanor@fenwickdaughters.co.uk',
    phone: '+44 131 555 0199',
    addressLine1: '12 Thistle Street',
    addressLine2: 'Second Floor',
    city: 'Edinburgh',
    region: 'Scotland',
    postalCode: 'EH2 1DF',
    country: 'United Kingdom',
    taxId: 'GB 412 5578 21',
    paymentTermsDays: 14,
    notes: 'Family-run tailor. Eleanor approves all artwork personally.',
    status: 'active',
  },
  {
    key: 'meridian',
    name: 'Meridian Transit Authority',
    company: 'Meridian Transit Authority',
    email: 'procurement@meridiantransit.vic.gov.au',
    phone: '+61 3 5550 8800',
    addressLine1: '1 Flinders Walk',
    addressLine2: 'Level 14',
    city: 'Melbourne',
    region: 'VIC',
    postalCode: '3000',
    country: 'Australia',
    taxId: 'ABN 51 824 753 556',
    paymentTermsDays: 45,
    notes: 'Public body — quote PO number on every invoice or it bounces.',
    status: 'active',
  },
  {
    key: 'halcyon',
    name: 'Halcyon Coffee Roasters',
    company: 'Halcyon Roasting Co.',
    email: 'hello@halcyonroasters.com',
    phone: '+1 503 555 0170',
    addressLine1: '2210 SE Division Street',
    addressLine2: '',
    city: 'Portland',
    region: 'OR',
    postalCode: '97202',
    country: 'United States',
    taxId: '93-1234567',
    paymentTermsDays: 15,
    notes: 'Packaging refresh for the single-origin range.',
    status: 'active',
  },
  {
    key: 'rookwood',
    name: 'Rookwood Press',
    company: 'Rookwood Press Ltd',
    email: 'production@rookwoodpress.ie',
    phone: '+353 1 555 0123',
    addressLine1: '4 Merrion Square',
    addressLine2: '',
    city: 'Dublin',
    region: 'Leinster',
    postalCode: 'D02 XY45',
    country: 'Ireland',
    taxId: 'IE 6388047V',
    paymentTermsDays: 30,
    notes: 'Book cover series; typography-heavy work.',
    status: 'active',
  },
  {
    key: 'tessellate',
    name: 'Tessellate Architecture',
    company: 'Tessellate Arkitekter ApS',
    email: 'studio@tessellate.dk',
    phone: '+45 33 55 01 88',
    addressLine1: 'Refshalevej 163A',
    addressLine2: '',
    city: 'Copenhagen',
    region: '',
    postalCode: '1432',
    country: 'Denmark',
    taxId: 'DK 36 12 87 90',
    paymentTermsDays: 30,
    notes: '',
    status: 'active',
  },
  {
    key: 'brightwater',
    name: 'Brightwater Aquatics',
    company: 'Brightwater Aquatics Ltd',
    email: 'accounts@brightwater.co.nz',
    phone: '+64 9 555 0134',
    addressLine1: '88 Halsey Street',
    addressLine2: 'Wynyard Quarter',
    city: 'Auckland',
    region: '',
    postalCode: '1010',
    country: 'New Zealand',
    taxId: 'NZ GST 118-234-567',
    paymentTermsDays: 21,
    notes: 'Visitor centre interpretation panels.',
    status: 'active',
  },
  {
    key: 'lumen',
    name: 'Lumen & Ash Candle Co.',
    company: 'Lumen & Ash LLC',
    email: 'orders@lumenandash.com',
    phone: '+1 718 555 0161',
    addressLine1: '67 Greenpoint Avenue',
    addressLine2: 'Unit 3B',
    city: 'Brooklyn',
    region: 'NY',
    postalCode: '11222',
    country: 'United States',
    taxId: '',
    paymentTermsDays: 30,
    notes: 'Small batch, pays promptly, likes moody photography.',
    status: 'active',
  },
  {
    key: 'northgate',
    name: 'Northgate Community Trust',
    company: 'Northgate Community Trust (charity 1187654)',
    email: 'comms@northgatetrust.org.uk',
    phone: '+44 161 555 0177',
    addressLine1: 'The Old Fire Station',
    addressLine2: '41 Ancoats Lane',
    city: 'Manchester',
    region: 'England',
    postalCode: 'M4 6DE',
    country: 'United Kingdom',
    taxId: '',
    paymentTermsDays: 60,
    notes: 'Charity rate applied. Slow payers but reliable.',
    status: 'active',
  },
  {
    key: 'oriel',
    name: 'Oriel Museum of Craft',
    company: 'Oriel Museum Trust',
    email: 'exhibitions@orielmuseum.wales',
    phone: '+44 29 5550 1200',
    addressLine1: 'Bute Place',
    addressLine2: '',
    city: 'Cardiff',
    region: 'Wales',
    postalCode: 'CF10 5AL',
    country: 'United Kingdom',
    taxId: 'GB 928 4471 03',
    paymentTermsDays: 30,
    notes: 'Bilingual (Welsh/English) deliverables required.',
    status: 'active',
  },
  {
    key: 'saltmarsh',
    name: 'Saltmarsh Distillery',
    company: 'Saltmarsh Destilleri AS',
    email: 'post@saltmarsh.no',
    phone: '+47 55 55 01 45',
    addressLine1: 'Bryggen 27',
    addressLine2: '',
    city: 'Bergen',
    region: 'Vestland',
    postalCode: '5003',
    country: 'Norway',
    taxId: 'NO 923 456 789 MVA',
    paymentTermsDays: 30,
    notes: 'Label design and bottle structure for the aquavit range.',
    status: 'active',
  },
  {
    key: 'verdant',
    name: 'Verdant Analytics',
    company: 'Verdant Analytics GmbH',
    email: 'finance@verdant-analytics.de',
    phone: '+49 30 5550 9900',
    addressLine1: 'Torstraße 104',
    addressLine2: '',
    city: 'Berlin',
    region: '',
    postalCode: '10119',
    country: 'Germany',
    taxId: 'DE 314159265',
    paymentTermsDays: 14,
    notes: 'SaaS dashboard design system; retainer under discussion.',
    status: 'active',
  },
  {
    key: 'pemberton',
    name: 'Pemberton Bicycle Works',
    company: 'Pemberton Cycles Ltd',
    email: 'workshop@pembertonbicycles.co.uk',
    phone: '+44 117 555 0188',
    addressLine1: 'Unit 9, Paintworks',
    addressLine2: 'Bath Road',
    city: 'Bristol',
    region: 'England',
    postalCode: 'BS4 3EH',
    country: 'United Kingdom',
    taxId: 'GB 771 2209 55',
    paymentTermsDays: 30,
    notes: '',
    status: 'active',
  },
  {
    key: 'kestrel',
    name: 'Kestrel Aerospace Supply',
    company: 'Kestrel Aerospace Supply SAS',
    email: 'achats@kestrel-aero.fr',
    phone: '+33 5 55 01 01 90',
    addressLine1: '14 Avenue Didier Daurat',
    addressLine2: '',
    city: 'Toulouse',
    region: 'Occitanie',
    postalCode: '31700',
    country: 'France',
    taxId: 'FR 12 345678901',
    paymentTermsDays: 45,
    notes: 'One-off trade show stand. Relationship closed in 2025.',
    status: 'archived',
  },
];

export interface SeedProject {
  key: string;
  client: string;
  name: string;
  code: string;
  description: string;
  status: ProjectStatus;
  billingType: BillingType;
  hourlyRateCents: number;
  budgetCents: number;
  startDate: string;
  endDate: string | null;
  /** Who logs time on it (user keys). */
  team: Array<'ada' | 'marcus' | 'priya'>;
  tasks: string[];
}

const BRAND_TASKS = [
  'Logo exploration',
  'Typography system',
  'Colour palette studies',
  'Brand guidelines layout',
  'Stakeholder review call',
  'Mockups and presentation',
];
const WEB_TASKS = [
  'Wireframes',
  'Component library',
  'Responsive layouts',
  'Accessibility pass',
  'Content entry',
  'Front-end QA',
  'Client walkthrough',
];
const PRINT_TASKS = [
  'Grid and masters',
  'Copy fitting',
  'Image retouching',
  'Proof corrections',
  'Press check',
  'Artwork handover',
];
const SIGNAGE_TASKS = [
  'Site survey',
  'Wayfinding map',
  'Pictogram set',
  'Fabrication drawings',
  'Installation supervision',
  'Panel artwork',
];
const PACKAGING_TASKS = [
  'Dieline setup',
  'Label illustration',
  'Print spec',
  'Finish samples review',
  'Range extension',
  'Mock-up photography',
];

export const NORTHLIGHT_PROJECTS: SeedProject[] = [
  {
    key: 'ald-wayfinding',
    client: 'aldergrove',
    name: 'Garden wayfinding refresh',
    code: 'ALD-01',
    description: 'New map, pictograms and trail markers across the 22-hectare site.',
    status: 'completed',
    billingType: 'hourly',
    hourlyRateCents: 11500,
    budgetCents: 4200000,
    startDate: '2025-01-13',
    endDate: '2025-06-27',
    team: ['ada', 'priya'],
    tasks: SIGNAGE_TASKS,
  },
  {
    key: 'ald-seasonal',
    client: 'aldergrove',
    name: 'Seasonal campaign 2026',
    code: 'ALD-02',
    description: 'Spring and summer poster series, social templates and banners.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 11500,
    budgetCents: 1800000,
    startDate: '2026-02-02',
    endDate: '2026-08-31',
    team: ['priya', 'ada'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'fen-identity',
    client: 'fenwick',
    name: 'Brand identity',
    code: 'FEN-01',
    description: 'Full rebrand for the 140-year-old tailoring house.',
    status: 'completed',
    billingType: 'fixed',
    hourlyRateCents: 13500,
    budgetCents: 2400000,
    startDate: '2025-02-03',
    endDate: '2025-07-31',
    team: ['ada'],
    tasks: BRAND_TASKS,
  },
  {
    key: 'fen-web',
    client: 'fenwick',
    name: 'Bespoke booking website',
    code: 'FEN-02',
    description: 'Appointment booking and lookbook site on the new identity.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 12500,
    budgetCents: 3600000,
    startDate: '2025-09-01',
    endDate: '2026-07-31',
    team: ['priya', 'marcus'],
    tasks: WEB_TASKS,
  },
  {
    key: 'mer-livery',
    client: 'meridian',
    name: 'Fleet livery and pictograms',
    code: 'MER-01',
    description: 'Tram and bus livery, station pictogram family and rollout guidelines.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 14500,
    budgetCents: 9500000,
    startDate: '2025-03-03',
    endDate: '2026-09-30',
    team: ['ada', 'priya', 'marcus'],
    tasks: SIGNAGE_TASKS,
  },
  {
    key: 'mer-annual',
    client: 'meridian',
    name: 'Annual report 2025',
    code: 'MER-02',
    description: 'Design and typesetting of the 96-page annual report.',
    status: 'completed',
    billingType: 'fixed',
    hourlyRateCents: 14500,
    budgetCents: 1850000,
    startDate: '2025-10-01',
    endDate: '2026-02-27',
    team: ['priya'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'hal-packaging',
    client: 'halcyon',
    name: 'Single-origin packaging',
    code: 'HAL-01',
    description: 'Six-bag range with illustrated origin maps.',
    status: 'completed',
    billingType: 'hourly',
    hourlyRateCents: 10500,
    budgetCents: 1500000,
    startDate: '2025-01-20',
    endDate: '2025-05-30',
    team: ['priya', 'ada'],
    tasks: PACKAGING_TASKS,
  },
  {
    key: 'hal-web',
    client: 'halcyon',
    name: 'Subscription web shop',
    code: 'HAL-02',
    description: 'Shopify theme and subscription flow.',
    status: 'on_hold',
    billingType: 'hourly',
    hourlyRateCents: 10500,
    budgetCents: 2200000,
    startDate: '2025-11-03',
    endDate: null,
    team: ['marcus', 'priya'],
    tasks: WEB_TASKS,
  },
  {
    key: 'roo-covers',
    client: 'rookwood',
    name: 'Classics reissue covers',
    code: 'ROO-01',
    description: 'Twelve-title cover series with bespoke lettering.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 9500,
    budgetCents: 2600000,
    startDate: '2025-04-07',
    endDate: '2026-07-31',
    team: ['ada', 'priya'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'roo-catalogue',
    client: 'rookwood',
    name: 'Autumn 2025 catalogue',
    code: 'ROO-02',
    description: '',
    status: 'completed',
    billingType: 'fixed',
    hourlyRateCents: 9500,
    budgetCents: 650000,
    startDate: '2025-06-02',
    endDate: '2025-08-29',
    team: ['priya'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'tes-portfolio',
    client: 'tessellate',
    name: 'Practice portfolio and website',
    code: 'TES-01',
    description: 'Print portfolio and matching site for the architecture practice.',
    status: 'completed',
    billingType: 'hourly',
    hourlyRateCents: 12500,
    budgetCents: 3200000,
    startDate: '2025-02-17',
    endDate: '2025-09-30',
    team: ['ada', 'marcus'],
    tasks: WEB_TASKS,
  },
  {
    key: 'tes-competition',
    client: 'tessellate',
    name: 'Competition boards',
    code: 'TES-02',
    description: 'Presentation boards for the harbour masterplan competition.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 12500,
    budgetCents: 900000,
    startDate: '2026-04-06',
    endDate: '2026-07-10',
    team: ['ada'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'bri-panels',
    client: 'brightwater',
    name: 'Visitor centre interpretation',
    code: 'BRI-01',
    description: 'Forty interpretive panels and a large-format reef map.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 11000,
    budgetCents: 4800000,
    startDate: '2025-08-04',
    endDate: '2026-10-30',
    team: ['priya', 'ada'],
    tasks: SIGNAGE_TASKS,
  },
  {
    key: 'lum-labels',
    client: 'lumen',
    name: 'Candle label range',
    code: 'LUM-01',
    description: 'Core range labels plus seasonal variants.',
    status: 'completed',
    billingType: 'hourly',
    hourlyRateCents: 9500,
    budgetCents: 800000,
    startDate: '2025-03-10',
    endDate: '2025-06-13',
    team: ['priya'],
    tasks: PACKAGING_TASKS,
  },
  {
    key: 'lum-gift',
    client: 'lumen',
    name: 'Gift box and holiday campaign',
    code: 'LUM-02',
    description: '',
    status: 'completed',
    billingType: 'hourly',
    hourlyRateCents: 9500,
    budgetCents: 700000,
    startDate: '2025-09-15',
    endDate: '2025-11-21',
    team: ['priya', 'ada'],
    tasks: PACKAGING_TASKS,
  },
  {
    key: 'nor-identity',
    client: 'northgate',
    name: 'Trust identity and templates',
    code: 'NOR-01',
    description: 'Charity-rate identity refresh with Word and Canva templates.',
    status: 'completed',
    billingType: 'fixed',
    hourlyRateCents: 7500,
    budgetCents: 950000,
    startDate: '2025-05-05',
    endDate: '2025-10-31',
    team: ['ada', 'priya'],
    tasks: BRAND_TASKS,
  },
  {
    key: 'nor-report',
    client: 'northgate',
    name: 'Impact report 2025',
    code: 'NOR-02',
    description: '',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 7500,
    budgetCents: 600000,
    startDate: '2026-03-02',
    endDate: '2026-07-31',
    team: ['priya'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'ori-exhibition',
    client: 'oriel',
    name: 'Makers of the Valleys exhibition',
    code: 'ORI-01',
    description: 'Bilingual exhibition graphics, catalogue and campaign.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 11000,
    budgetCents: 3400000,
    startDate: '2025-11-10',
    endDate: '2026-08-14',
    team: ['ada', 'priya', 'marcus'],
    tasks: SIGNAGE_TASKS,
  },
  {
    key: 'sal-aquavit',
    client: 'saltmarsh',
    name: 'Aquavit range labels',
    code: 'SAL-01',
    description: 'Three-expression label system and gift tube.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 12000,
    budgetCents: 1900000,
    startDate: '2025-12-01',
    endDate: '2026-09-30',
    team: ['ada', 'priya'],
    tasks: PACKAGING_TASKS,
  },
  {
    key: 'ver-design-system',
    client: 'verdant',
    name: 'Dashboard design system',
    code: 'VER-01',
    description: 'Figma design system and documentation site for the analytics product.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 15500,
    budgetCents: 7200000,
    startDate: '2025-06-16',
    endDate: '2026-12-18',
    team: ['marcus', 'priya', 'ada'],
    tasks: WEB_TASKS,
  },
  {
    key: 'pem-catalogue',
    client: 'pemberton',
    name: 'Frame builder catalogue',
    code: 'PEM-01',
    description: 'Photographed catalogue and geometry charts.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 10000,
    budgetCents: 1200000,
    startDate: '2026-01-12',
    endDate: '2026-08-28',
    team: ['priya', 'ada'],
    tasks: PRINT_TASKS,
  },
  {
    key: 'kes-stand',
    client: 'kestrel',
    name: 'Paris Air Show stand graphics',
    code: 'KES-01',
    description: 'Trade show stand, brochures and product boards.',
    status: 'archived',
    billingType: 'hourly',
    hourlyRateCents: 13000,
    budgetCents: 2100000,
    startDate: '2025-02-24',
    endDate: '2025-06-13',
    team: ['ada', 'marcus'],
    tasks: SIGNAGE_TASKS,
  },
];

export interface FixedLine {
  description: string;
  quantity: number;
  unitPriceCents: number;
}

/** Fixed-fee line items used when an invoice is not built from time entries. */
export const FIXED_LINE_SETS: FixedLine[][] = [
  [
    {
      description: 'Brand identity — phase 1: discovery and positioning',
      quantity: 1,
      unitPriceCents: 480000,
    },
  ],
  [
    {
      description: 'Brand identity — phase 2: visual identity',
      quantity: 1,
      unitPriceCents: 720000,
    },
    { description: 'Brand guidelines (PDF, 48pp)', quantity: 1, unitPriceCents: 180000 },
  ],
  [
    { description: 'Website design — milestone 2 of 4', quantity: 1, unitPriceCents: 650000 },
    { description: 'Stock photography licences', quantity: 6, unitPriceCents: 4500 },
  ],
  [
    {
      description: 'Print collateral — business cards and letterhead artwork',
      quantity: 1,
      unitPriceCents: 95000,
    },
    { description: 'Print management fee', quantity: 1, unitPriceCents: 25000 },
  ],
  [
    {
      description: 'Packaging design — dielines and label artwork',
      quantity: 3,
      unitPriceCents: 145000,
    },
    { description: 'Finish and proof samples', quantity: 1, unitPriceCents: 18500 },
  ],
  [
    { description: 'Exhibition graphics — panel artwork', quantity: 12, unitPriceCents: 32000 },
    { description: 'Large-format map artwork', quantity: 1, unitPriceCents: 240000 },
  ],
  [
    {
      description: 'Annual report — design and typesetting (96pp)',
      quantity: 1,
      unitPriceCents: 925000,
    },
  ],
  [
    {
      description: 'Design system — component library sprint',
      quantity: 2,
      unitPriceCents: 420000,
    },
    { description: 'Documentation site setup', quantity: 1, unitPriceCents: 160000 },
  ],
  [
    {
      description: 'Campaign creative — poster series (A1, 4 designs)',
      quantity: 4,
      unitPriceCents: 68000,
    },
    { description: 'Social media templates', quantity: 1, unitPriceCents: 85000 },
  ],
  [
    { description: 'Catalogue design (64pp)', quantity: 1, unitPriceCents: 540000 },
    { description: 'Art direction — photography day', quantity: 2, unitPriceCents: 95000 },
  ],
];

export interface SeedVendor {
  vendor: string;
  description: string;
  /** Account code the expense posts to. */
  account: string;
  minCents: number;
  maxCents: number;
  taxed: boolean;
}

export const VENDORS: SeedVendor[] = [
  {
    vendor: 'Adobe',
    description: 'Creative Cloud team licences',
    account: '5120',
    minCents: 24900,
    maxCents: 24900,
    taxed: true,
  },
  {
    vendor: 'Figma',
    description: 'Figma Organisation seats',
    account: '5120',
    minCents: 13500,
    maxCents: 13500,
    taxed: true,
  },
  {
    vendor: 'Amazon Web Services',
    description: 'Hosting and storage',
    account: '5110',
    minCents: 8200,
    maxCents: 19600,
    taxed: false,
  },
  {
    vendor: 'Linode',
    description: 'Staging server',
    account: '5110',
    minCents: 2400,
    maxCents: 4800,
    taxed: false,
  },
  {
    vendor: 'Notion Labs',
    description: 'Workspace subscription',
    account: '5100',
    minCents: 4800,
    maxCents: 4800,
    taxed: true,
  },
  {
    vendor: 'Monotype',
    description: 'Typeface licences',
    account: '5120',
    minCents: 18000,
    maxCents: 62000,
    taxed: true,
  },
  {
    vendor: 'LNER',
    description: 'Train tickets — client visit',
    account: '5200',
    minCents: 6400,
    maxCents: 21800,
    taxed: false,
  },
  {
    vendor: 'Premier Inn',
    description: 'Hotel — site survey',
    account: '5200',
    minCents: 8900,
    maxCents: 17800,
    taxed: true,
  },
  {
    vendor: 'KLM',
    description: 'Flights — client workshop',
    account: '5200',
    minCents: 21000,
    maxCents: 48000,
    taxed: false,
  },
  {
    vendor: 'Ines Moreau',
    description: 'Illustration commission',
    account: '5300',
    minCents: 60000,
    maxCents: 180000,
    taxed: false,
  },
  {
    vendor: 'Halide Photography',
    description: 'Product photography day',
    account: '5310',
    minCents: 85000,
    maxCents: 140000,
    taxed: true,
  },
  {
    vendor: 'Tomás Herrera',
    description: 'Front-end development — contract',
    account: '5300',
    minCents: 120000,
    maxCents: 320000,
    taxed: false,
  },
  {
    vendor: 'Herman Miller',
    description: 'Studio chairs',
    account: '5410',
    minCents: 98000,
    maxCents: 245000,
    taxed: true,
  },
  {
    vendor: 'Rymans',
    description: 'Stationery and proofing paper',
    account: '5400',
    minCents: 3200,
    maxCents: 9800,
    taxed: true,
  },
  {
    vendor: 'Ravensworth Print',
    description: 'Client proofs and mock-ups',
    account: '5400',
    minCents: 12000,
    maxCents: 46000,
    taxed: true,
  },
  {
    vendor: 'Meta Platforms',
    description: 'Studio promotion — paid social',
    account: '5500',
    minCents: 15000,
    maxCents: 40000,
    taxed: false,
  },
  {
    vendor: 'Dribbble',
    description: 'Dribbble Pro listing',
    account: '5500',
    minCents: 9600,
    maxCents: 9600,
    taxed: false,
  },
  {
    vendor: 'Hiscox',
    description: 'Professional indemnity insurance',
    account: '5900',
    minCents: 74000,
    maxCents: 74000,
    taxed: false,
  },
  {
    vendor: 'Leeds City Council',
    description: 'Studio business rates',
    account: '5900',
    minCents: 41500,
    maxCents: 41500,
    taxed: false,
  },
  {
    vendor: 'Northern Gas',
    description: 'Studio heating',
    account: '5400',
    minCents: 9800,
    maxCents: 26000,
    taxed: true,
  },
];

export const HARBOUR_CLIENTS: SeedClient[] = [
  {
    key: 'copperline',
    name: 'Copperline Brewing',
    company: 'Copperline Brewing Ltd',
    email: 'taproom@copperline.ie',
    phone: '+353 21 555 0140',
    addressLine1: 'Marina Commercial Park',
    addressLine2: '',
    city: 'Cork',
    region: 'Munster',
    postalCode: 'T12 X2R4',
    country: 'Ireland',
    taxId: 'IE 3456789T',
    paymentTermsDays: 30,
    notes: '',
    status: 'active',
  },
  {
    key: 'drift',
    name: 'Drift Surf School',
    company: 'Drift Surf & Coffee',
    email: 'hi@driftsurf.ie',
    phone: '+353 96 555 0150',
    addressLine1: 'Main Street',
    addressLine2: '',
    city: 'Lahinch',
    region: 'Co. Clare',
    postalCode: 'V95 XY22',
    country: 'Ireland',
    taxId: '',
    paymentTermsDays: 14,
    notes: 'Seasonal — busiest May to September.',
    status: 'active',
  },
  {
    key: 'glasshouse',
    name: 'Glasshouse Florists',
    company: 'Glasshouse Florists SARL',
    email: 'bonjour@glasshouse-fleurs.fr',
    phone: '+33 1 55 50 12 34',
    addressLine1: '18 Rue des Martyrs',
    addressLine2: '',
    city: 'Paris',
    region: 'Île-de-France',
    postalCode: '75009',
    country: 'France',
    taxId: 'FR 98 765432109',
    paymentTermsDays: 30,
    notes: '',
    status: 'active',
  },
];

export const HARBOUR_PROJECTS: SeedProject[] = [
  {
    key: 'cop-cans',
    client: 'copperline',
    name: 'Core range can design',
    code: 'COP-01',
    description: 'Four cans plus a seasonal template.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 9000,
    budgetCents: 1200000,
    startDate: '2025-09-08',
    endDate: '2026-08-28',
    team: ['marcus', 'ada'],
    tasks: PACKAGING_TASKS,
  },
  {
    key: 'cop-taproom',
    client: 'copperline',
    name: 'Taproom signage',
    code: 'COP-02',
    description: '',
    status: 'completed',
    billingType: 'fixed',
    hourlyRateCents: 9000,
    budgetCents: 450000,
    startDate: '2025-10-06',
    endDate: '2026-01-30',
    team: ['ada'],
    tasks: SIGNAGE_TASKS,
  },
  {
    key: 'dri-brand',
    client: 'drift',
    name: 'Brand and merch',
    code: 'DRI-01',
    description: 'Logo, tees and van livery.',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 8000,
    budgetCents: 600000,
    startDate: '2026-02-16',
    endDate: '2026-06-26',
    team: ['ada', 'marcus'],
    tasks: BRAND_TASKS,
  },
  {
    key: 'gla-web',
    client: 'glasshouse',
    name: 'Online ordering site',
    code: 'GLA-01',
    description: '',
    status: 'active',
    billingType: 'hourly',
    hourlyRateCents: 9500,
    budgetCents: 1500000,
    startDate: '2026-03-02',
    endDate: '2026-09-30',
    team: ['marcus'],
    tasks: WEB_TASKS,
  },
];
